CREATE DATABASE SPMEDICALGROUP
GO

USE SPMEDICALGROUP
GO

CREATE TABLE TIPO_USUARIO(
idTipoUsuario INT IDENTITY PRIMARY KEY,
tipo VARCHAR(30) NOT NULL
);
GO

CREATE TABLE USUARIO(
idUsuario INT IDENTITY PRIMARY KEY,
idTipoUsuario INT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
nomeUsuario VARCHAR(100) NOT NULL,
emailUsuario VARCHAR(275) NOT NULL,
senha VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CLINICA(
idClinica INT IDENTITY PRIMARY KEY,
endereco VARCHAR(265) NOT NULL,

);

CREATE TABLE MEDICO(
idMedico INT IDENTITY PRIMARY KEY,
idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
);
GO